# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [2]:
# your code here
data = pd.read_csv('tic-tac-toe.csv')
data.head()

  TL TM TR ML MM MR BL BM BR  class
0  x  x  x  x  o  o  x  o  o   True
1  x  x  x  x  o  o  o  x  o   True
2  x  x  x  x  o  o  o  o  x   True
3  x  x  x  x  o  o  o  b  b   True
4  x  x  x  x  o  o  b  o  b   True

In [3]:
data.shape

(958, 10)

In [4]:

data.dtypes

TL       object
TM       object
TR       object
ML       object
MM       object
MR       object
BL       object
BM       object
BR       object
class      bool
dtype: object

In [5]:
data = data.astype('category')

In [6]:
# convert {x, o, b} to {2, 1, 0}

data = data.apply(lambda x: x.cat.codes)
data.head()

   TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0   2   2   2   2   1   1   2   1   1      1
1   2   2   2   2   1   1   1   2   1      1
2   2   2   2   2   1   1   1   1   2      1
3   2   2   2   2   1   1   1   0   0      1
4   2   2   2   2   1   1   0   1   0      1

In [7]:
# Separate the inputs and output

y = data['class']
X = data[data.columns.difference(['class'])]
print("y shape:", y.shape)
print("X shape:", X.shape)

y shape: (958,)
X shape: (958, 9)

In [8]:
# normalize the input data

def normalize(x):
    result = x.copy()
    for feature_name in x.columns:
        max_value = data[feature_name].max()
        min_value = data[feature_name].min()
        result[feature_name] = (data[feature_name] - min_value) / (max_value - min_value)
    return result
X = normalize(X)

In [9]:
X

      BL   BM   BR   ML   MM   MR   TL   TM   TR
0    1.0  0.5  0.5  1.0  0.5  0.5  1.0  1.0  1.0
1    0.5  1.0  0.5  1.0  0.5  0.5  1.0  1.0  1.0
2    0.5  0.5  1.0  1.0  0.5  0.5  1.0  1.0  1.0
3    0.5  0.0  0.0  1.0  0.5  0.5  1.0  1.0  1.0
4    0.0  0.5  0.0  1.0  0.5  0.5  1.0  1.0  1.0
5    0.0  0.0  0.5  1.0  0.5  0.5  1.0  1.0  1.0
6    0.5  0.5  0.0  1.0  0.5  0.0  1.0  1.0  1.0
7    0.5  0.0  0.5  1.0  0.5  0.0  1.0  1.0  1.0
8    0.0  0.5  0.5  1.0  0.5  0.0  1.0  1.0  1.0
9    0.5  0.5  0.0  1.0  0.0  0.5  1.0  1.0  1.0
10   0.5  0.0  0.5  1.0  0.0  0.5  1.0  1.0  1.0
11   0.0  0.5  0.5  1.0  0.0  0.5  1.0  1.0  1.0
12   1.0  0.5  0.5  0.5  1.0  0.5  1.0  1.0  1.0
13   0.5  1.0  0.5  0.5  1.0  0.5  1.0  1.0  1.0
14   0.5  0.5  1.0  0.5  1.0  0.5  1.0  1.0  1.0
15   0.5  0.0  0.0  0.5  1.0  0.5  1.0  1.0  1.0
16   0.0  0.5  0.0  0.5  1.0  0.5  1.0  1.0  1.0
17   0.0  0.0  0.5  0.5  1.0  0.5  1.0  1.0  1.0
18   0.5  0.5  0.0  0.5  1.0  0.0  1.0  1.0  1.0
19   0.5  0.0  0.5  0.5  1.0  0.0  1.0  1.0  1.0
20   0.0  0.5  0.5  0.5  1.0  0.0  1.0  1.0  1.0
21   1.0  0.5  0.5  0.5  0.5  1.0  1.0  1.0  1.0
22   0.5  1.0  0.5  0.5  0.5  1.0  1.0  1.0  1.0
23   0.5  0.5  1.0  0.5  0.5  1.0  1.0  1.0  1.0
24   0.5  0.0  0.0  0.5  0.5  1.0  1.0  1.0  1.0
25   0.0  0.5  0.0  0.5  0.5  1.0  1.0  1.0  1.0
26   0.0  0.0  0.5  0.5  0.5  1.0  1.0  1.0  1.0
27   1.0  0.5  0.0  0.5  0.5  0.0  1.0  1.0  1.0
28   1.0  0.0  0.5  0.5  0.5  0.0  1.0  1.0  1.0
29   0.5  1.0  0.0  0.5  0.5  0.0  1.0  1.0  1.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...
928  0.5  0.5  0.5  1.0  1.0  0.0  0.0  0.0  1.0
929  0.5  0.5  0.5  1.0  0.0  1.0  0.0  0.0  1.0
930  1.0  1.0  0.0  0.5  0.5  0.5  0.0  0.0  1.0
931  1.0  0.0  1.0  0.5  0.5  0.5  0.0  0.0  1.0
932  0.0  1.0  1.0  0.5  0.5  0.5  0.0  0.0  1.0
933  0.5  0.5  0.5  0.0  1.0  1.0  0.0  0.0  1.0
934  1.0  0.0  0.5  1.0  1.0  0.5  0.0  0.0  0.5
935  0.0  1.0  0.5  1.0  1.0  0.5  0.0  0.0  0.5
936  0.5  1.0  0.0  1.0  0.5  1.0  0.0  0.0  0.5
937  0.5  0.0  1.0  1.0  0.5  1.0  0.0  0.0  0.5
938  0.5  1.0  1.0  1.0  0.5  0.0  0.0  0.0  0.5
939  1.0  1.0  0.5  1.0  0.0  0.5  0.0  0.0  0.5
940  1.0  1.0  0.5  0.0  1.0  0.5  0.0  0.0  0.5
941  0.5  1.0  1.0  0.0  0.5  1.0  0.0  0.0  0.5
942  1.0  0.5  0.5  0.5  1.0  1.0  1.0  1.0  0.5
943  1.0  1.0  0.5  0.5  0.5  1.0  1.0  1.0  0.5
944  1.0  0.5  1.0  0.5  0.5  1.0  1.0  1.0  0.5
945  0.5  1.0  0.5  1.0  1.0  0.5  1.0  0.5  1.0
946  0.5  1.0  0.5  1.0  0.5  1.0  1.0  0.5  1.0
947  0.5  1.0  1.0  1.0  0.5  0.5  1.0  0.5  1.0
948  0.5  1.0  0.5  0.5  1.0  1.0  1.0  0.5  1.0
949  1.0  1.0  0.5  0.5  0.5  1.0  1.0  0.5  1.0
950  1.0  1.0  0.5  0.5  1.0  1.0  1.0  0.5  0.5
951  0.5  0.5  1.0  1.0  1.0  0.5  0.5  1.0  1.0
952  1.0  0.5  1.0  1.0  0.5  0.5  0.5  1.0  1.0
953  0.5  1.0  1.0  1.0  0.5  0.5  0.5  1.0  1.0
954  1.0  0.5  1.0  1.0  1.0  0.5  0.5  1.0  0.5
955  1.0  0.5  1.0  1.0  0.5  1.0  0.5  1.0  0.5
956  1.0  0.5  1.0  0.5  1.0  1.0  0.5  1.0  0.5
957  0.5  1.0  1.0  1.0  1.0  0.5  0.5  0.5  1.0

[958 rows x 9 columns]

In [10]:
# transforming X and y to an array

y = np.array(y)
X = np.array(X)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [11]:
# your code here
from sklearn.model_selection import train_test_split

In [12]:
# Split the training and test data

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.8,test_size=0.2)

print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(766, 9) (192, 9) (766,) (192,)

In [13]:
# Initialize neural network
model = tf.keras.models.Sequential()
model

In [14]:
# Add input layer
model.add(tf.keras.layers.Flatten())

# Add first hidden layer
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))

# Add second hidden layer
model.add(tf.keras.layers.Dense(128, activation=tf.nn.relu))

# Add output layer
model.add(tf.keras.layers.Dense(3, activation=tf.nn.softmax))

# Define parameters for the model
model.compile(optimizer='adam',
             loss='sparse_categorical_crossentropy',
             metrics=['accuracy'])

In [15]:
# Fit the model

model.fit(X_train, y_train, epochs=3)

Train on 766 samples
Epoch 1/3
766/766 [==============================] - 1s 1ms/sample - loss: 0.7443 - accuracy: 0.6449
Epoch 2/3
766/766 [==============================] - 0s 142us/sample - loss: 0.6437 - accuracy: 0.6332
Epoch 3/3
766/766 [==============================] - 0s 116us/sample - loss: 0.6150 - accuracy: 0.6645

In [16]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print(val_loss)
print(val_acc)

192/192 [==============================] - 0s 819us/sample - loss: 0.5734 - accuracy: 0.7292
0.573402926325798
0.7291667

In [17]:
model.save('neural.model')

WARNING:tensorflow:From /Users/katja/anaconda3/lib/python3.7/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: neural.model/assets

## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [ ]:
# your code here
new_model = tf.keras.models.load_model('neural.model')

In [ ]:
predictions = new_model.predict(X_test)

In [ ]:
print(np.argmax(predictions[3]))

In [ ]:
y_test[3]

In [ ]:
s = f = 0
for i, p in enumerate(predicitons):
    pred = np.argmax(p)
    if pred == y_test[i]:
        s += 1
    else:
        f += 1

success_rate = s/len(y_test)*100
fail_rate = f/len(y_test)*100
print("Success Rate:", success_rate, "Fail Rate:", fail_rate)

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here

model.fit(X_train, y_train, epochs=100)

In [ ]:
val_loss, val_acc = model.evaluate(X_test, y_test)
print(val_loss)
print(val_acc)

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here
# increasing epochs  improves the results